spring:
  datasource:
    url: "jdbc:postgresql://ec2-34-198-189-252.compute-1.amazonaws.com:5432/dc5rf2vprqc2ms"
    username: "bzwfsmroxzmwkz"
    password: "72c82820f62a1401fa6ba052f12c8e5eacaa46c5178636de59f10b3151600e96"
    driverClassName: "org.postgresql.Driver"

  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: "false"
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: "false"
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
