spring:
  datasource:
    url: "jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres"
    username: "postgres.fqxyocolbkxjsohpxvpg"
    password: "wavsox-guhrah-6kidJi"
    driverClassName: "org.postgresql.Driver"

  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: "false"
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: "false"
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
